server:
  port: 8080

  #  This is the default port for the application
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

#      This is for the file storage image location
file_storage:
  image_location: "filestorage/images/"
  client_path: "/images/**"




# This is for the access token
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key
