name: Docker Build, Push

on:
  push:
    branches:
      - lyhou

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
          echo -e "\033[32mImage pushed to Docker Hub Successfully\033[0m"
          
          

#  deploy:
#    runs-on: ubuntu-latest
#    environment: DOCKER
#    needs: build-and-push
#    steps:
#      - name: Install SSHPass
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y sshpass
#
#      - name: SSH Command to Deploy
#        run: |
#          sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh -o StrictHostKeyChecking=no -p 22 '${{ secrets.SSH_USER }}'@'${{ secrets.SSH_HOST }}' << EOF
#            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#            sudo docker stop ${{ secrets.CONTAINER_NAME }} || true
#            sudo docker rm ${{ secrets.CONTAINER_NAME }} || true
#            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} || true
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
#            sudo docker run -d --name ${{ secrets.CONTAINER_NAME }} -p 4018:8080 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
#            sudo docker logout
#          EOF
#
#
#
#
